### ISSUE TITLE
Kyverno policy for Docker Hub images

### ISSUE THREAD

**Issue by rblaine95** [maxtacu/ecr-pull-through#12]
Would it be possible to create a Kyverno policy for Docker Hub images?
* `busybox` -> `<aws_account_id>.dkr.ecr.<aws_region>.amazonaws.com/docker.io/library/busybox`
* `docker.io/busybox` -> `<aws_account_id>.dkr.ecr.<aws_region>.amazonaws.com/docker.io/library/busybox`
* `bitnami/keycloak` -> `<aws_account_id>.dkr.ecr.<aws_region>.amazonaws.com/docker.io/bitnami/keycloak`
* `docker.io/bitnami/keycloak` -> `<aws_account_id>.dkr.ecr.<aws_region>.amazonaws.com/docker.io/bitnami/keycloak`

**Comment by rblaine95** [comment]
This works really well:
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: ecr-pull-through-cache
  annotations:
    policies.kyverno.io/title: Use ECR Pull Through Cache
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.11.4
spec:
  rules:
    - name: redirect-dockerio
      match:
        any:
          - resources:
              kinds:
                - Pod
              operations:
                - CREATE
      mutate:
        foreach:
          - list: request.object.spec.initContainers[]
            context:
              - name: imageData
                imageRegistry:
                  reference: "{{ element.image }}"
            preconditions:
              any:
                - key: "{{imageData.registry}}"
                  operator: Equals
                  value: index.docker.io
            patchStrategicMerge:
              spec:
                initContainers:
                  - name: "{{ element.name }}"
                    image: ${aws_account_id}.dkr.ecr.${aws_region}.amazonaws.com/docker.io/{{imageData.repository}}:{{imageData.identifier}}
          - list: request.object.spec.containers[]
            context:
              - name: imageData
                imageRegistry:
                  reference: "{{ element.image }}"
            preconditions:
              any:
                - key: "{{imageData.registry}}"
                  operator: Equals
                  value: index.docker.io
            patchStrategicMerge:
              spec:
                containers:
                  - name: "{{ element.name }}"
                    image: ${aws_account_id}.dkr.ecr.${aws_region}.amazonaws.com/docker.io/{{imageData.repository}}:{{imageData.identifier}}
```

Only issue is Kyverno will get you rate limited unless you provide it with an image pull secret to do lookups against Docker Hub

https://kyverno.io/docs/writing-policies/external-data-sources/#variables-from-image-registries
https://kyverno.io/docs/writing-policies/verify-images/sigstore/#using-private-registries

**Comment by rblaine95** [comment]
The `imageData` lookup seems to be _extremely_ slow...

**Comment by rblaine95** [comment]
The `imageData` lookup is incredibly slow and causes us to get rate limited extremely quickly.

<details>
<summary>This is the current working (but not quite perfect) policy we're using:</summary>

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: dockerio-ecr-pull-through
  annotations:
    policies.kyverno.io/title: Use ECR Pull Through Cache for Docker.io
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.6.0
    policies.kyverno.io/description: >-
      Rewrite container images to use ECR pull-through cache instead of upstream Docker Hub registry.
      This policy automatically redirects Docker Hub images through an ECR pull-through cache to
      improve pull reliability and reduce rate limiting issues.
spec:
  rules:
    - name: rewrite-containers-official
      match:
        any:
          - resources:
              kinds:
                - Pod
      preconditions:
        all:
          - key: "{{request.operation || 'BACKGROUND'}}"
            operator: AnyIn
            value:
              - CREATE
              - UPDATE
          - key: "{{ images.containers.*.registry[] || `[]` }}"
            operator: AnyIn
            value:
              - docker.io
          - key: "{{ images.containers.*.path[] || `[]` }}"
            operator: AllNotIn
            value: ["*/*"]
      mutate:
        foreach:
          - list: request.object.spec.containers
            preconditions:
              all:
                - key: '{{ images.containers."{{element.name}}".registry }}'
                  operator: AnyIn
                  value:
                    - docker.io
            patchStrategicMerge:
              spec:
                containers:
                  - name: "{{ element.name }}"
                    image: '402177810328.dkr.ecr.af-south-1.amazonaws.com/docker.io/library/{{ images.containers."{{element.name}}".path }}:{{ images.containers."{{element.name}}".tag || "latest" }}'

    - name: rewrite-containers-org
      match:
        any:
          - resources:
              kinds:
                - Pod
      preconditions:
        all:
          - key: "{{request.operation || 'BACKGROUND'}}"
            operator: AnyIn
            value:
              - CREATE
              - UPDATE
          - key: "{{ images.containers.*.registry[] || `[]` }}"
            operator: AnyIn
            value:
              - docker.io
          - key: "{{ images.containers.*.path[] || `[]` }}"
            operator: AnyIn
            value: ["*/*"]
      mutate:
        foreach:
          - list: request.object.spec.containers
            preconditions:
              all:
                - key: '{{ images.containers."{{element.name}}".registry }}'
                  operator: AnyIn
                  value:
                    - docker.io
                - key: '{{ images.containers."{{element.name}}".path }}'
                  operator: AnyIn
                  value: ["*/*"]
            patchStrategicMerge:
              spec:
                containers:
                  - name: "{{ element.name }}"
                    image: '402177810328.dkr.ecr.af-south-1.amazonaws.com/docker.io/{{ images.containers."{{element.name}}".path }}:{{ images.containers."{{element.name}}".tag || "latest" }}'

    - name: rewrite-initcontainers-official
      match:
        any:
          - resources:
              kinds:
                - Pod
      preconditions:
        all:
          - key: "{{request.operation || 'BACKGROUND'}}"
            operator: AnyIn
            value:
              - CREATE
              - UPDATE
          - key: "{{ request.object.spec.initContainers[] || '' | length(@) }}"
            operator: GreaterThanOrEquals
            value: 1
          - key: "{{ images.initContainers.*.registry[] || `[]` }}"
            operator: AnyIn
            value:
              - docker.io
          - key: "{{ images.initContainers.*.path[] || `[]` }}"
            operator: AllNotIn
            value: ["*/*"]
      mutate:
        foreach:
          - list: request.object.spec.initContainers
            preconditions:
              all:
                - key: '{{ images.initContainers."{{element.name}}".registry }}'
                  operator: AnyIn
                  value:
                    - docker.io
            patchStrategicMerge:
              spec:
                initContainers:
                  - name: "{{ element.name }}"
                    image: '402177810328.dkr.ecr.af-south-1.amazonaws.com/docker.io/library/{{ images.initContainers."{{element.name}}".path }}:{{ images.initContainers."{{element.name}}".tag || "latest" }}'

    - name: rewrite-initcontainers-org
      match:
        any:
          - resources:
              kinds:
                - Pod
      preconditions:
        all:
          - key: "{{request.operation || 'BACKGROUND'}}"
            operator: AnyIn
            value:
              - CREATE
              - UPDATE
          - key: "{{ request.object.spec.initContainers[] || '' | length(@) }}"
            operator: GreaterThanOrEquals
            value: 1
          - key: "{{ images.initContainers.*.registry[] || `[]` }}"
            operator: AnyIn
            value:
              - docker.io
          - key: "{{ images.initContainers.*.path[] || `[]` }}"
            operator: AnyIn
            value: ["*/*"]
      mutate:
        foreach:
          - list: request.object.spec.initContainers
            preconditions:
              all:
                - key: '{{ images.initContainers."{{element.name}}".registry }}'
                  operator: AnyIn
                  value:
                    - docker.io
                - key: '{{ images.initContainers."{{element.name}}".path }}'
                  operator: AnyIn
                  value: ["*/*"]
            patchStrategicMerge:
              spec:
                initContainers:
                  - name: "{{ element.name }}"
                    image: '402177810328.dkr.ecr.af-south-1.amazonaws.com/docker.io/{{ images.initContainers."{{element.name}}".path }}:{{ images.initContainers."{{element.name}}".tag || "latest" }}'

    - name: rewrite-ephemeralcontainers-official
      match:
        any:
          - resources:
              kinds:
                - Pod
      preconditions:
        all:
          - key: "{{request.operation || 'BACKGROUND'}}"
            operator: AnyIn
            value:
              - CREATE
              - UPDATE
          - key: "{{ request.object.spec.ephemeralContainers[] || '' | length(@) }}"
            operator: GreaterThanOrEquals
            value: 1
          - key: "{{ images.ephemeralContainers.*.registry[] || `[]` }}"
            operator: AnyIn
            value:
              - docker.io
          - key: "{{ images.ephemeralContainers.*.path[] || `[]` }}"
            operator: AllNotIn
            value: ["*/*"]
      mutate:
        foreach:
          - list: request.object.spec.ephemeralContainers
            preconditions:
              all:
                - key: '{{ images.ephemeralContainers."{{element.name}}".registry }}'
                  operator: AnyIn
                  value:
                    - docker.io
            patchStrategicMerge:
              spec:
                ephemeralContainers:
                  - name: "{{ element.name }}"
                    image: '402177810328.dkr.ecr.af-south-1.amazonaws.com/docker.io/library/{{ images.ephemeralContainers."{{element.name}}".path }}:{{ images.ephemeralContainers."{{element.name}}".tag || "latest" }}'

    - name: rewrite-ephemeralcontainers-org
      match:
        any:
          - resources:
              kinds:
                - Pod
      preconditions:
        all:
          - key: "{{request.operation || 'BACKGROUND'}}"
            operator: AnyIn
            value:
              - CREATE
              - UPDATE
          - key: "{{ request.object.spec.ephemeralContainers[] || '' | length(@) }}"
            operator: GreaterThanOrEquals
            value: 1
          - key: "{{ images.ephemeralContainers.*.registry[] || `[]` }}"
            operator: AnyIn
            value:
              - docker.io
          - key: "{{ images.ephemeralContainers.*.path[] || `[]` }}"
            operator: AnyIn
            value: ["*/*"]
      mutate:
        foreach:
          - list: request.object.spec.ephemeralContainers
            preconditions:
              all:
                - key: '{{ images.ephemeralContainers."{{element.name}}".registry }}'
                  operator: AnyIn
                  value:
                    - docker.io
                - key: '{{ images.ephemeralContainers."{{element.name}}".path }}'
                  operator: AnyIn
                  value: ["*/*"]
            patchStrategicMerge:
              spec:
                ephemeralContainers:
                  - name: "{{ element.name }}"
                    image: '402177810328.dkr.ecr.af-south-1.amazonaws.com/docker.io/{{ images.ephemeralContainers."{{element.name}}".path }}:{{ images.ephemeralContainers."{{element.name}}".tag || "latest" }}'
```

</details>

It has an issue when you mix official and org images.
For example:
```
kubectl run busybox -it --rm --image=busybox \
  --overrides='{"spec": {"initContainers": [{"name": "init-container", "image": "busybox", "command": ["sh", "-c", "exit 0"]}, {"name": "curl-init", "image": "curlimages/curl", "command": ["sh", "-c", "exit 0"]}]}}' \
  -- sh
```
Results in the following pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - args:
    - sh
    image: ${aws_account_id}.dkr.ecr.${aws_region}.amazonaws.com/docker.io/library/busybox:latest
    imagePullPolicy: Always
    name: busybox
  initContainers:
  - command:
    - sh
    - -c
    - exit 0
    image: ${aws_account_id}.dkr.ecr.${aws_region}.amazonaws.com/docker.io/curlimages/curl:latest
    imagePullPolicy: Always
    name: curl-init
  - command:
    - sh
    - -c
    - exit 0
    image: busybox
    imagePullPolicy: Always
    name: init-container
```

When mixing official (`busybox`) and org (`curlimages/curl`) in the same place (e.g: init containers) then only the `rewrite-initcontainers-org` mutation occurs.

**Comment by rblaine95** [comment]
Seem to have resolved the issue of mixing images:

<details>
<summary>docker-io.yaml</summary>

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: dockerio-ecr-pull-through
  annotations:
    policies.kyverno.io/title: Use ECR Pull Through Cache for Docker.io
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.6.0
    policies.kyverno.io/description: >-
      Rewrite container images to use ECR pull-through cache instead of upstream Docker Hub registry.
      This policy automatically redirects Docker Hub images through an ECR pull-through cache to
      improve pull reliability and reduce rate limiting issues.
spec:
  rules:
    - name: rewrite-containers
      match:
        any:
          - resources:
              kinds:
                - Pod
      preconditions:
        all:
          - key: "{{request.operation || 'BACKGROUND'}}"
            operator: AnyIn
            value:
              - CREATE
              - UPDATE
          - key: "{{ images.containers.*.registry[] || `[]` }}"
            operator: AnyIn
            value:
              - docker.io
      mutate:
        foreach:
          - list: request.object.spec.containers
            preconditions:
              all:
                - key: '{{ images.containers."{{element.name}}".registry }}'
                  operator: AnyIn
                  value:
                    - docker.io
                - key: '{{ images.containers."{{element.name}}".path }}'
                  operator: NotIn
                  value: ["*/*"]
            patchStrategicMerge:
              spec:
                containers:
                  - name: "{{ element.name }}"
                    image: '${aws_account_id}.dkr.ecr.${aws_region}.amazonaws.com/docker.io/library/{{ images.containers."{{element.name}}".path }}:{{ images.containers."{{element.name}}".tag || "latest" }}'
          - list: request.object.spec.containers
            preconditions:
              all:
                - key: '{{ images.containers."{{element.name}}".registry }}'
                  operator: AnyIn
                  value:
                    - docker.io
                - key: '{{ images.containers."{{element.name}}".path }}'
                  operator: AnyIn
                  value: ["*/*"]
            patchStrategicMerge:
              spec:
                containers:
                  - name: "{{ element.name }}"
                    image: '${aws_account_id}.dkr.ecr.${aws_region}.amazonaws.com/docker.io/{{ images.containers."{{element.name}}".path }}:{{ images.containers."{{element.name}}".tag || "latest" }}'

    - name: rewrite-initcontainers
      match:
        any:
          - resources:
              kinds:
                - Pod
      preconditions:
        all:
          - key: "{{request.operation || 'BACKGROUND'}}"
            operator: AnyIn
            value:
              - CREATE
              - UPDATE
          - key: "{{ request.object.spec.initContainers[] || '' | length(@) }}"
            operator: GreaterThanOrEquals
            value: 1
          - key: "{{ images.initContainers.*.registry[] || `[]` }}"
            operator: AnyIn
            value:
              - docker.io
      mutate:
        foreach:
          - list: request.object.spec.initContainers
            preconditions:
              all:
                - key: '{{ images.initContainers."{{element.name}}".registry }}'
                  operator: AnyIn
                  value:
                    - docker.io
                - key: '{{ images.initContainers."{{element.name}}".path }}'
                  operator: NotIn
                  value: ["*/*"]
            patchStrategicMerge:
              spec:
                initContainers:
                  - name: "{{ element.name }}"
                    image: '${aws_account_id}.dkr.ecr.${aws_region}.amazonaws.com/docker.io/library/{{ images.initContainers."{{element.name}}".path }}:{{ images.initContainers."{{element.name}}".tag || "latest" }}'
          - list: request.object.spec.initContainers
            preconditions:
              all:
                - key: '{{ images.initContainers."{{element.name}}".registry }}'
                  operator: AnyIn
                  value:
                    - docker.io
                - key: '{{ images.initContainers."{{element.name}}".path }}'
                  operator: AnyIn
                  value: ["*/*"]
            patchStrategicMerge:
              spec:
                initContainers:
                  - name: "{{ element.name }}"
                    image: '${aws_account_id}.dkr.ecr.${aws_region}.amazonaws.com/docker.io/{{ images.initContainers."{{element.name}}".path }}:{{ images.initContainers."{{element.name}}".tag || "latest" }}'

    - name: rewrite-ephemeralcontainers
      match:
        any:
          - resources:
              kinds:
                - Pod
      preconditions:
        all:
          - key: "{{request.operation || 'BACKGROUND'}}"
            operator: AnyIn
            value:
              - CREATE
              - UPDATE
          - key: "{{ request.object.spec.ephemeralContainers[] || '' | length(@) }}"
            operator: GreaterThanOrEquals
            value: 1
          - key: "{{ images.ephemeralContainers.*.registry[] || `[]` }}"
            operator: AnyIn
            value:
              - docker.io
      mutate:
        foreach:
          - list: request.object.spec.ephemeralContainers
            preconditions:
              all:
                - key: '{{ images.ephemeralContainers."{{element.name}}".registry }}'
                  operator: AnyIn
                  value:
                    - docker.io
                - key: '{{ images.ephemeralContainers."{{element.name}}".path }}'
                  operator: NotIn
                  value: ["*/*"]
            patchStrategicMerge:
              spec:
                ephemeralContainers:
                  - name: "{{ element.name }}"
                    image: '${aws_account_id}.dkr.ecr.${aws_region}.amazonaws.com/docker.io/library/{{ images.ephemeralContainers."{{element.name}}".path }}:{{ images.ephemeralContainers."{{element.name}}".tag || "latest" }}'
          - list: request.object.spec.ephemeralContainers
            preconditions:
              all:
                - key: '{{ images.ephemeralContainers."{{element.name}}".registry }}'
                  operator: AnyIn
                  value:
                    - docker.io
                - key: '{{ images.ephemeralContainers."{{element.name}}".path }}'
                  operator: AnyIn
                  value: ["*/*"]
            patchStrategicMerge:
              spec:
                ephemeralContainers:
                  - name: "{{ element.name }}"
                    image: '${aws_account_id}.dkr.ecr.${aws_region}.amazonaws.com/docker.io/{{ images.ephemeralContainers."{{element.name}}".path }}:{{ images.ephemeralContainers."{{element.name}}".tag || "latest" }}'
```

</details>

It was the `AllNotIn` preconditions causing the image replacements to be skipped when mixing namespaced and official dockerhub images
